
sources:
  - name: gz_raw_data  
    description: "This dataset contains raw transactional data."
    tables:
      - name: raw_gz_sales 
        description: "This table contains raw sales transaction data."
      - name: raw_gz_product 
        description: "This table contains raw product details."
      - name: raw_gz_ship  
        description: "This table contains raw shipping information."
