
sources:
  - name: raw
    description: "This dataset contains raw transactional data."
    tables:
      - name: sales 
        description: "This table contains raw sales transaction data."
      - name: product 
        description: "This table contains raw product details."
      - name: ship  
        description: "This table contains raw shipping information."
